sudo: false
language: python
python:
  - "3.6"
install:  # command to install dependencies
  - pip install -r requirements.txt
  - python setup.py develop
script:  # command to run tests
  - py.test --cov=./compoda
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
